name: ML Pipeline

on:
  push:
    branches: [ main ]

jobs:

  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install packages
        run: |
          pip install mlflow

      - name: Train model
        run: python train.py

      - name: Save Run ID
        run: echo "RUN_ID=$(cat run_id.txt)" > model_info.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-info
          path: model_info.txt


  deploy:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: model-info

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install MLflow
        run: pip install mlflow

      - name: Check accuracy
        run: python check_threshold.py

      - name: Mock Docker Build
        run: echo "Building Docker image for Run ID: $(cat 
model_info.txt)"
